### ISSUE TITLE
Finalize content included in the Twitter share

### ISSUE THREAD

**Issue by jonuy** [DoSomethingGames/teen-pregnancy-ee#10]
The share at the end of the game should include:
- finalized copy
- the URL back to the game/11 facts page
- bonus: is there a way to get a customized image pre-loaded in the Tweet too? One that reflects how the player did?

**Comment by jmithani** [comment]
For the image, we'd have to have them premade I think? Not a part of the spritesheet. Also, we could tweet it out as a link? However, looks like embedded is more likely to be retweeted. For that we need to tweet out all the pictures, then grab the link and attach that to the sharing url in the game.

Dropping here for relevance: 
http://blog.socialsourcecommons.org/2011/03/creating-share-this-on-facebooktwitter-links/
http://onlinejournalismblog.com/2015/02/11/how-to-make-a-tweetable-image-in-your-blog-post/
http://stackoverflow.com/questions/17825195/twitter-share-button-but-with-image
