### ISSUE TITLE
Create a rotation of facts that are displayed at the end of the game

### ISSUE THREAD

**Issue by jonuy** [DoSomethingGames/teen-pregnancy-ee#9]
Currently only a single fact is displayed at the end of the game. Instead, let's randomize the fact displayed using the ones found here: https://www.dosomething.org/facts/11-facts-about-teen-pregnancy

![end-screen](https://cloud.githubusercontent.com/assets/696595/11660771/b58d9aa6-9d9c-11e5-9b7a-45c901307a86.png)

**Comment by jmithani** [comment]
@jonuy 
This is in the 'randomFact' branch. Error with the array of facts being undefined. Surpassed my 20min rule.
